
import { Language } from '../types';

export interface LanguageDef {
  code: Language;
  name: string;
  locale: string;
}

export const SUPPORTED_LANGUAGES: LanguageDef[] = [
  { code: 'en', name: 'English', locale: 'en-US' },
  { code: 'hi', name: 'हिन्दी (Hindi)', locale: 'hi-IN' },
  { code: 'bn', name: 'বাংলা (Bengali)', locale: 'bn-IN' },
  { code: 'ta', name: 'தமிழ் (Tamil)', locale: 'ta-IN' },
  { code: 'te', name: 'తెలుగు (Telugu)', locale: 'te-IN' },
  { code: 'mr', name: 'मराठी (Marathi)', locale: 'mr-IN' },
  { code: 'es', name: 'Español (Spanish)', locale: 'es-ES' },
  { code: 'fr', name: 'Français (French)', locale: 'fr-FR' },
  { code: 'ar', name: 'العربية (Arabic)', locale: 'ar-SA' },
  { code: 'zh', name: '中文 (Chinese)', locale: 'zh-CN' },
];

const EN_UI = {
  appTitle: "Rural AI Doctor",
  homeTitle: "How are you feeling?",
  homeSubtitle: "Describe symptoms or upload photo.",
  inputPlaceholder: "Type symptoms (e.g., fever, cut, pain)...",
  checkBtn: "Check Symptoms",
  demoLabel: "Try Demo Case",
  disclaimer: "⚠️ Not a doctor. In emergency, go to hospital.",
  emergencyTitle: "EMERGENCY DETECTED",
  callAmbulance: "🚨 Call Emergency (102/911)",
  sendSMS: "📩 Send Emergency SMS",
  startOver: "Start Over",
  risk: "Risk Level",
  assessment: "Assessment",
  firstAid: "First Aid Steps",
  avoid: "Avoid This",
  recommendation: "Recommendation",
  history: "History",
  listening: "Listening...",
  loading: "Analyzing...",
  thinking: "Thinking...",
  submitAnswers: "Submit Answers",
  followUpTitle: "I need details",
  yourAnswer: "Your Answer",
  speakResult: "Speak Result",
  stopSpeaking: "Stop Speaking",
  profiles: "Family Profiles",
  addProfile: "Add New Profile",
  selectProfile: "Select Patient",
  createProfile: "Create Profile",
  name: "Name",
  age: "Age",
  gender: "Gender",
  male: "Male",
  female: "Female",
  other: "Other",
  conditions: "Known Conditions",
  contactNum: "Emergency Contact #",
  contactName: "Contact Name",
  save: "Save",
  cancel: "Cancel",
  fillRequired: "Fill required fields",
  nearbyHelp: "📍 Nearby Help",
  hospitals: "Hospitals",
  pharmacy: "Pharmacy",
  offlineMode: "⚠️ You are OFFLINE",
  offlineDesc: "No internet. Use these guides.",
  viewOfflineGuides: "Emergency Guides",
  timeline: "Timeline",
  enterLocation: "Enter City",
  analyzeTrend: "📊 Analyze Trend",
  analyzingTrend: "Analyzing...",
  trendTitle: "Health Trend",
  improving: "Improving",
  worsening: "Worsening",
  stable: "Stable",
  noHistoryForTrend: "Not enough history.",
  currentPatient: "Patient",
  yourHealth: "Your Health",
};

// Static dictionary for all languages
const TRANSLATIONS: Record<Language, Record<keyof typeof EN_UI, string>> = {
  en: EN_UI,
  hi: {
    ...EN_UI,
    appTitle: "ग्रामीण एआई डॉक्टर",
    homeTitle: "आप कैसा महसूस कर रहे हैं?",
    homeSubtitle: "लक्षण बताएं या फोटो अपलोड करें।",
    inputPlaceholder: "लक्षण लिखें (जैसे बुखार, चोट, दर्द)...",
    checkBtn: "जांच करें",
    disclaimer: "⚠️ यह डॉक्टर नहीं है। आपात स्थिति में अस्पताल जाएं।",
    emergencyTitle: "आपातकालीन स्थिति",
    callAmbulance: "🚨 एम्बुलेंस बुलाएं (102/911)",
    sendSMS: "📩 आपातकालीन SMS भेजें",
    startOver: "शुरू से",
    risk: "जोखिम स्तर",
    assessment: "मूल्यांकन",
    firstAid: "प्राथमिक चिकित्सा",
    avoid: "यह न करें",
    recommendation: "सलाह",
    listening: "सुन रहा हूँ...",
    loading: "विश्लेषण हो रहा है...",
    thinking: "सोच रहा हूँ...",
    submitAnswers: "जवाब भेजें",
    followUpTitle: "अधिक जानकारी चाहिए",
    speakResult: "बोलकर बताएं",
    stopSpeaking: "चुप रहें",
    profiles: "पारिवारिक प्रोफाइल",
    addProfile: "नया प्रोफाइल जोड़ें",
    selectProfile: "मरीज चुनें",
    createProfile: "प्रोफाइल बनाएं",
    name: "नाम",
    age: "उम्र",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    conditions: "मौजूदा बीमारियां",
    contactNum: "आपातकालीन नंबर",
    save: "सहेजें",
    nearbyHelp: "📍 नजदीकी मदद",
    hospitals: "अस्पताल",
    pharmacy: "दवा की दुकान",
    offlineMode: "⚠️ आप ऑफलाइन हैं",
    offlineDesc: "इंटरनेट नहीं है। इन गाइड का उपयोग करें।",
    viewOfflineGuides: "इमरजेंसी गाइड",
    timeline: "समय रेखा",
    analyzeTrend: "📊 रुझान देखें",
    trendTitle: "स्वास्थ्य रुझान",
    improving: "सुधार हो रहा है",
    worsening: "हालत बिगड़ रही है",
    stable: "स्थिर है",
    currentPatient: "मरीज",
  },
  bn: {
    ...EN_UI,
    appTitle: "গ্রামীণ এআই ডাক্তার",
    homeTitle: "আপনি কেমন অনুভব করছেন?",
    homeSubtitle: "লক্ষণ বর্ণনা করুন বা ছবি দিন।",
    checkBtn: "লক্ষণ পরীক্ষা করুন",
    disclaimer: "⚠️ এটি ডাক্তার নয়। জরুরি অবস্থায় হাসপাতালে যান।",
    emergencyTitle: "জরুরি অবস্থা",
    risk: "ঝুঁকির মাত্রা",
    firstAid: "প্রাথমিক চিকিৎসা",
    loading: "বিশ্লেষণ করা হচ্ছে...",
    profiles: "পারিবারিক প্রোফাইল",
    offlineMode: "⚠️ আপনি অফলাইনে আছেন",
    currentPatient: "রোগী",
  },
  ta: {
    ...EN_UI,
    appTitle: "கிராமப்புற AI மருத்துவர்",
    homeTitle: "எப்படி உணர்கிறீர்கள்?",
    checkBtn: "அறிகுறிகளைச் சரிபார்க்கவும்",
    disclaimer: "⚠️ இது மருத்துவர் அல்ல. அவசரநிலையில் மருத்துவமனைக்குச் செல்லவும்.",
    emergencyTitle: "அவசர நிலை",
    risk: "ஆபத்து நிலை",
    firstAid: "முதலுதவி",
    loading: "பகுப்பாய்வு செய்கிறது...",
    offlineMode: "⚠️ ஆஃப்லைனில் உள்ளீர்கள்",
  },
  te: {
    ...EN_UI,
    appTitle: "రూరల్ AI డాక్టర్",
    homeTitle: "మీరు ఎలా ఉన్నారు?",
    checkBtn: "లక్షణాలను తనిఖీ చేయండి",
    disclaimer: "⚠️ ఇది డాక్టర్ కాదు. అత్యవసరమైతే ఆసుపత్రికి వెళ్లండి.",
    emergencyTitle: "అత్యవసర పరిస్థితి",
    risk: "ప్రమాద స్థాయి",
    firstAid: "ప్రథమ చికిత్స",
    loading: "విశ్లేషిస్తోంది...",
    offlineMode: "⚠️ మీరు ఆఫ్‌లైన్‌లో ఉన్నారు",
  },
  mr: {
    ...EN_UI,
    appTitle: "ग्रामीण एआय डॉक्टर",
    homeTitle: "तुम्हाला कसे वाटते आहे?",
    checkBtn: "लक्षणे तपासा",
    disclaimer: "⚠️ हा डॉक्टर नाही. आपत्कालीन स्थितीत हॉस्पिटलला जा.",
    emergencyTitle: "आणीबाणी",
    risk: "धोका पातळी",
    firstAid: "प्रथमोपचार",
    loading: "विश्लेषण करत आहे...",
    offlineMode: "⚠️ आपण ऑफलाइन आहात",
  },
  es: {
    ...EN_UI,
    appTitle: "Doctor IA Rural",
    homeTitle: "¿Cómo te sientes?",
    homeSubtitle: "Describe síntomas o sube foto.",
    inputPlaceholder: "Escribe síntomas (ej. fiebre, corte)...",
    checkBtn: "Consultar",
    disclaimer: "⚠️ No es un médico. En emergencia, ve al hospital.",
    emergencyTitle: "EMERGENCIA DETECTADA",
    callAmbulance: "🚨 Llamar Emergencia",
    sendSMS: "📩 Enviar SMS",
    risk: "Nivel de Riesgo",
    firstAid: "Primeros Auxilios",
    loading: "Analizando...",
    profiles: "Perfiles Familiares",
    offlineMode: "⚠️ Estás OFFLINE",
    currentPatient: "Paciente",
  },
  fr: {
    ...EN_UI,
    appTitle: "Docteur IA Rural",
    homeTitle: "Comment vous sentez-vous ?",
    checkBtn: "Vérifier symptômes",
    disclaimer: "⚠️ Ce n'est pas un médecin. En urgence, allez à l'hôpital.",
    emergencyTitle: "URGENCE DÉTECTÉE",
    risk: "Niveau de Risque",
    firstAid: "Premiers Secours",
    loading: "Analyse en cours...",
    offlineMode: "⚠️ Vous êtes HORS LIGNE",
  },
  ar: {
    ...EN_UI,
    appTitle: "طبيب الذكاء الاصطناعي الريفي",
    homeTitle: "كيف تشعر؟",
    checkBtn: "تحقق من الأعراض",
    disclaimer: "⚠️ هذا ليس طبيباً. في حالة الطوارئ، اذهب للمستشفى.",
    emergencyTitle: "حالة طوارئ",
    risk: "مستوى الخطورة",
    firstAid: "الإسعافات الأولية",
    loading: "جاري التحليل...",
    offlineMode: "⚠️ أنت غير متصل",
  },
  zh: {
    ...EN_UI,
    appTitle: "乡村AI医生",
    homeTitle: "你感觉怎么样？",
    checkBtn: "检查症状",
    disclaimer: "⚠️ 这不是医生。紧急情况请去医院。",
    emergencyTitle: "检测到紧急情况",
    risk: "风险等级",
    firstAid: "急救步骤",
    loading: "分析中...",
    offlineMode: "⚠️ 您已离线",
  }
};

export const getTranslation = (key: keyof typeof EN_UI, lang: Language): string => {
  const langPack = TRANSLATIONS[lang] || TRANSLATIONS['en'];
  return langPack[key] || EN_UI[key] || key;
};

export const getBrowserLang = (): Language => {
  const browserLang = navigator.language.split('-')[0];
  const found = SUPPORTED_LANGUAGES.find(l => l.code === browserLang);
  return found ? (found.code as Language) : 'en';
};
